apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: vote
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
      - image: ghcr.io/salaboy/vote-java
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: DAPR_HTTP_ENDPOINT
          value: http://vote-dapr.default.svc.cluster.local:3500
        - name: DAPR_GRPC_ENDPOINT
          value: http://vote-dapr.default.svc.cluster.local:50001  
        - name: VOTE_STATE_STORE
          value: votes-statestore
        - name: VOTE_PUBSUB
          value: pubsub-rabbitmq
        - name: VOTE_TOPIC
          value: newVote    
        