apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: vote-1
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
        autoscaling.knative.dev/target: "10"
        dapr.io/app-id: vote
        dapr.io/enabled: "true"
        dapr.io/log-level: "debug"
        dapr.io/metrics-port: "9092"
    spec:
      containers:
      - image: docker.io/salaboy/vote-java
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        # - name: DAPR_HTTP_ENDPOINT
        #   value: http://vote-dapr.default.svc.cluster.local:3500
        # - name: DAPR_GRPC_ENDPOINT
        #   value: http://vote-dapr.default.svc.cluster.local:50001 
        # - name: DAPR_HTTP_ENDPOINT
        #   value: "https://http-prj11702.api.cloud.diagrid.io"
        # - name: DAPR_GRPC_ENDPOINT
        #   value: "https://grpc-prj11702.api.cloud.diagrid.io"
        # - name: DAPR_API_TOKEN
        #   valueFrom: 
        #     secretKeyRef: 
        #       name: vote-secret
        #       key: token
        # - name: DAPR_STATESTORE_NAME
        #   value: kvstore
        # - name: DAPR_PUBSUB_NAME
        #   value: pubsub
        - name: DAPR_TOPIC_NAME
          value: newVote
        - name: VOTE_PUBSUB
          value: pubsub
        - name: DAPR_STATESTORE_NAME
          value: votes-statestore
        - name: DAPR_PUBSUB_NAME
          value: pubsub-rabbitmq
        # - name: DAPR_TOPIC_NAME
        #   value: newVote
        # - name: VOTE_PUBSUB
        #   value: pubsub-rabbitmq     
        - name: VOTE_TOPIC
          value: newVote
