apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result
  name: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      annotations:  
        dapr.io/app-id: result
        dapr.io/app-port: "3000"
        dapr.io/enabled: "true"
        dapr.io/sidecar-image: "docker.io/daprio/daprd:1.13.0-rc.2" 
        dapr.io/log-level: "debug"
      labels:
        app: result
    spec:
      containers:
      - image: ghcr.io/salaboy/result-go
        name: result
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: result
