apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      annotations:  
        dapr.io/app-id: worker
        dapr.io/enabled: "true"
        dapr.io/sidecar-image: "docker.io/daprio/daprd:1.13.0-rc.2" 
        dapr.io/log-level: "debug"
      labels:
        app: worker
    spec:
      containers:
      - image: ghcr.io/salaboy/worker-dotnet
        name: worker
        imagePullPolicy: Always
