apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: echo
  namespace: default
  annotations: 
    networking.knative.dev/http-protocol: "enabled"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
      - image: ghcr.io/salaboy/echo-java
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        