apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: worker
  namespace: default
  labels:
    networking.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
      - image: ghcr.io/salaboy/worker-dotnet
        imagePullPolicy: Always
        env:
        - name: DAPR_HTTP_ENDPOINT
          value: http://worker-dapr.default.svc.cluster.local:3500
        - name: DAPR_GRPC_ENDPOINT
          value: http://worker-dapr.default.svc.cluster.local:50001
        - name: BASE_URL
          value: http://worker-dapr.default.svc.cluster.local
